### ISSUE TITLE
java.time.* causes NoClassDefFoundError in local app server

### ISSUE THREAD

**Issue by Taig** [sbt/sbt-appengine#55]
Using `java.time.*` works fine when the local server is started from maven. With this plugin however, an exception is thrown:
```
java.lang.NoClassDefFoundError: java.time.format.DateTimeFormatter is a restricted class. Please see the Google  App Engine developer's guide for more details.
	at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:50)
	at org.http4s.util.Renderer$$anon$1.<init>(Renderable.scala:33)
	at org.http4s.util.Renderer$.<init>(Renderable.scala:29)
	at org.http4s.util.Renderer$.<clinit>(Renderable.scala)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:69)
	at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:63)
        ...
```
I could only find one related issue online [on StackOverflow](https://stackoverflow.com/questions/45821425/google-app-engine-on-java-8-java-time-not-available-on-dev-server?noredirect=1#comment87540976_45821425) which reports the same behavior with the sbt plugin.

Here is a [sample repo](https://github.com/Taig/sbt-appengine-java-time) for easy reproduction of the error.

**Comment by breilly2** [comment]
I ran into the same problem and traced it down to the presence of
```
-javaagent:/Users/breilly/Local/Tools/appengine-java-sdk-1.9.64/lib/agent/appengine-agent.jar
```
when starting the dev server. The official maven plugin does not specify any javaagent. Maybe the javaagent a holdover from the old `java` (as opposed to `java8`) runtime?

Unfortunately, unlike for #36, I don't think this can be patched in the project. I think it's going to require a change to sbt-appengine itself. I'm pretty new to app engine so I don't know if this javaagent is ever needed. Therefore I'm not in a position to make a pull request for the changes.
