### ISSUE TITLE
Error with appengine-java-sdk-1.9.64: "java.lang.RuntimeException: No permissions needed for this runtime."

### ISSUE THREAD

**Issue by breilly2** [sbt/sbt-appengine#56]
appengine-java-sdk-1.9.63 was working fine, but when upgrading to 1.9.64, accessing the app after starting the local dev server results in the following error:

```
java.lang.RuntimeException: No permissions needed for this runtime.
	at com.google.appengine.tools.development.jetty9.JettyContainerService$JettyAppContext.getApplicationPermissions(JettyContainerService.java:154)
	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.appHasPermission(DevAppServerFactory.java:497)
	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:547)
	at java.lang.Thread.setContextClassLoader(Thread.java:1474)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1079)
	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:601)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
```

After some experimentation, I discovered a JVM parameter, `-Duse_jetty9_runtime=true`, that the maven plugin uses when starting the dev server but sbt-appengine does not. I don't know sbt very well at all, but I was finally able to hack in a change to make sbt-appengine add this parameter and then 1.9.64 worked.

There are a few other differences I noticed. Here is what the maven plugin logs:

```
INFO: submitting command: [java_home_path]/jre/bin/java -Duse_jetty9_runtime=true -D--enable_all_permissions=true -Dappengine.sdk.root=[google-cloud-sdk_path]/platform/google_appengine/google/appengine/tools/java -cp [google-cloud-sdk_path]/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain --allow_remote_shutdown --disable_update_check --no_java_agent [exploded_war_path]
```

I don't know where it's getting `google-cloud-sdk_path` from... maybe by finding the location of `gcloud` in `PATH`. Let me know if you need any more details. Thanks!

**Comment by breilly2** [comment]
As a temporary workaround, I was able to put this in our build.sbt:

```
javaOptions in appengineDevServer in Compile += "-Duse_jetty9_runtime=true"
```
