### ISSUE TITLE
The sample doesn't work

### ISSUE THREAD

**Issue by Humblehound** [sbt/sbt-appengine#57]
Hi, I've tried using your plugin with latest sbt and scala version but sbt fails with the plugin due to missing google cloud sdk. I've then tried to clone the repository and run the simple sample standalone, with the only adjustment being entering the 0.8.0 version into the plugins file. That didn't work as well, the error is the same in both cases. The error is as follows:

```
[error] java.lang.RuntimeException: not found appengine api jar.
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at sbtappengine.AppenginePlugin$AppEngine$.buildSdkVersion(AppenginePlugin.scala:143)
[error] 	at sbtappengine.AppenginePlugin$.$anonfun$baseAppengineSettings$61(AppenginePlugin.scala:251)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] not found appengine api jar.
```
I've also tried adding the jar to sbt dependencies but the plugin still doesn't recognize it

**Comment by Humblehound** [comment]
My bad: I've set the SDK variable to the google cloud SDK, instead of app engine SDK. Works fine
